apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appgate-operator
rules:
- apiGroups: ["beta.appgate.com"]
  resources:
  - policies
  - entitlements
  - conditions
  - ringfencerules
  - appliances
  - sites
  - ippools
  - identityproviders
  - localusers
  - administrativeroles
  - mfaproviders
  - adminmfasettingss
  - trustedcertificates
  - criteriascriptss
  - devicescripts
  - entitlementscripts
  - appliancecustomizations
  - globalsettingss
  - clientconnections
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps","secrets"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appgate-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: appgate-operator
  apiGroup: rbac.authorization.k8s.io
