apiVersion: beta.appgate.com/v1
kind: IdentityProvider
metadata:
  name: connector
spec:
  appgate_metadata:
    passwords: []
    uuid: b2cdefce-1efe-4a7e-85d1-7976920f118f
  claimMappings:
  - attributeName: peerHostname
    claimName: peerHostname
  - attributeName: tags
    claimName: tags
    list: true
  - attributeName: clientName
    claimName: clientName
  - attributeName: applianceApiVersion
    claimName: applianceApiVersion
  - attributeName: hostname
    claimName: hostname
  - attributeName: id
    claimName: id
  - attributeName: applianceName
    claimName: applianceName
  dnsSearchDomains: []
  dnsServers: []
  name: Connector
  notes: Built-in Connector provider.
  onDemandClaimMappings: []
  tags:
  - builtin
  type: Connector
---
apiVersion: beta.appgate.com/v1
kind: IdentityProvider
metadata:
  name: local
spec:
  adminProvider: true
  appgate_metadata:
    passwords: []
    uuid: b5ea7cf0-6e75-11e4-9803-0800200c9a66
  claimMappings:
  - attributeName: username
    claimName: username
  - attributeName: lastName
    claimName: lastName
  - attributeName: tags
    claimName: tags
    list: true
  - attributeName: firstName
    claimName: firstName
  - attributeName: phone
    claimName: phone
  - attributeName: id
    claimName: id
  - attributeName: email
    claimName: emails
    list: true
  dnsSearchDomains: []
  dnsServers: []
  ipPoolV4: simple_setup_ipv4
  ipPoolV6: simple_setup_ipv6
  name: local
  notes: Built-in Identity Provider on local database.
  onDemandClaimMappings: []
  tags:
  - builtin
  type: LocalDatabase
