apiVersion: beta.appgate.com/v1
kind: LocalUser
metadata:
  name: bobbytables
spec:
  appgate_metadata:
    passwords:
    - password
    uuid: 95c4360a-7b4b-4de6-9527-e0b714f9d344
  email: bobby@tables.com
  failedLoginAttempts: 0
  firstName: Bobby
  lastName: Tables
  name: bobbytables
  notes: My notes
  password: foobar
  tags:
  - operator
