apiVersion: beta.appgate.com/v1
kind: Site
metadata:
  name: simple-setup-site
spec:
  appgate_metadata:
    uuid: 3d844467-8d82-42d2-946a-53b3d8ff11ec
  defaultGateway:
    excludedSubnets: []
  ipPoolMappings: []
  name: simple_setup Site
  nameResolution:
    awsResolvers: []
    azureResolvers: []
    dnsResolvers: []
    esxResolvers: []
    gcpResolvers: []
    useHostsFile: true
  networkSubnets:
  - 172.17.115.0/24
  tags:
  - setup
  vpn:
    dtls: {}
    routeVia: {}
    snat: true
    tls: {}
    webProxyEnabled: false
---
apiVersion: beta.appgate.com/v1
kind: Site
metadata:
  name: default-site
spec:
  appgate_metadata:
    uuid: 8a4add9e-0e99-4bb1-949c-c9faf9a49ad4
  defaultGateway:
    excludedSubnets: []
  entitlementBasedRouting: true
  ipPoolMappings: []
  name: Default Site
  nameResolution:
    awsResolvers: []
    azureResolvers: []
    dnsResolvers: []
    esxResolvers: []
    gcpResolvers: []
  networkSubnets: []
  notes: Built-in default site with EBR.
  tags:
  - builtin
  vpn:
    dtls: {}
    routeVia: {}
    snat: true
    tls: {}
    webProxyEnabled: false
