apiVersion: beta.appgate.com/v1
kind: IdentityProvider
metadata:
  name: local
spec:
  adminProvider: true
  claimMappings:
  - attributeName: lastName
    claimName: lastName
  - attributeName: firstName
    claimName: firstName
  - attributeName: email
    claimName: emails
    list: true
  - attributeName: username
    claimName: username
  - attributeName: phone
    claimName: phone
  - attributeName: tags
    claimName: tags
    list: true
  - attributeName: id
    claimName: id
  dnsSearchDomains: []
  dnsServers: []
  ipPoolV4: f572b4ab-7963-4a90-9e5a-3bf033bfe2cc
  ipPoolV6: 6935b379-205d-4fdd-847f-a0b5f14aff53
  name: local
  notes: Built-in Identity Provider on local database.
  onDemandClaimMappings: []
  tags:
  - builtin
  type: LocalDatabase
---
apiVersion: beta.appgate.com/v1
kind: IdentityProvider
metadata:
  name: connector
spec:
  claimMappings:
  - attributeName: hostname
    claimName: hostname
  - attributeName: applianceName
    claimName: applianceName
  - attributeName: applianceApiVersion
    claimName: applianceApiVersion
  - attributeName: clientName
    claimName: clientName
  - attributeName: tags
    claimName: tags
    list: true
  - attributeName: peerHostname
    claimName: peerHostname
  - attributeName: id
    claimName: id
  dnsSearchDomains: []
  dnsServers: []
  name: Connector
  notes: Built-in Connector provider.
  onDemandClaimMappings: []
  tags:
  - builtin
  type: Connector
