apiVersion: "beta.appgate.com/v1"
kind: Entitlement
metadata:
  name: my-new-entitlement-good
spec:
  name: my-new-entitlement-good
  site: 8a4add9e-0e99-4bb1-949c-c9faf9a49ad4
  tags: 
    - k8s
    - automated
    - api-created
  conditions: 
    - my-new-condition
  disabled: true
  conditionLogic: and
  actions:
    - subtype: icmp_up
      action: block
      types:
        - 0-16
      hosts:
        - 10.0.0.1
        - 10.0.0.0/24
        - hostname.company.com
        - dns://hostname.company.com
        - aws://security-group:accounting
    - subtype: icmp_up
      action: allow
      types:
        - 0-16
      hosts:
        - 10.0.0.5
  appShortcuts:
    - name: ping
      url: https://www.google.com
      colorCode : 5
