apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policies.beta.appgate.com
spec:
  group: beta.appgate.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: policies
    singular: policy
    kind: Policy
    shortNames:
    - pol
  validation:
    openAPIV3Schema:
      type: object
      properties:
        name:
          type: string
        notes:
          type: string
        tags:
          type: array
          items:
            type: string
        disabled:
          type: boolean
        expression:
          type: string
        entitlements:
          type: array
          items:
            type: string
        entitlementLinks:
          type: array
          items:
            type: string
        ringfenceRues:
          type: array
          items:
            type: string
        ringfenceRuleLinks:
          type: array
          items:
            type: string
        tamperProofing:
          type: bool
        overrideSite:
          type: string
        administrativeRoles:
          type: array
          items:
            type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: conditions.beta.appgate.com
spec:
  group: beta.appgate.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: conditions
    singular: condition
    kind: Condition
    shortNames:
    - con
  validation:
    openAPIV3Schema:
      type: object
      properties:
        name:
          type: string
        notes:
          type: string
        tags:
          type: array
          items:
            type: string
        expression:
          type: string
        repeatSchedules:
          type: array
          items:
            type: string
        remedyMethods:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              message:
                type: string
              claimSuffix:
                type: string
              providerId:
                type: string
            
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entitlements.beta.appgate.com
spec:
  group: beta.appgate.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: entitlements
    singular: entitlement
    kind: Entitlement
    shortNames:
    - ent
  validation:
    openAPIV3Schema:
      type: object
      properties:
        name:
          type: string
        notes:
          type: string
        tags:
          type: array
          items:
            type: string
        disabled:
          type: boolean
        site:
          type: string
        site_name:
          type: string
        conditionLogic:
          type: string
        conditions:
          type: array
          items:
            type: string
        actions:
          type: array
          items:
            type: object
            properties:
              subtype:
                type: string
              action:
                type: allow
              types:
                type: string
              hosts:
                type: array
                items:
                  type: string
              ports:
                type: array
                items:
                  type: string
              monitor:
                type: object
                properties:
                  enabled:
                    type: boolean
                  timeout:
                    type: integer
        appShortcut:
          type: object
          properties:
            name:
              type: string
            url:
              type: string
            colorMode:
              type: integer
