apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: appgate-test-1
  name: appgate-operator
rules:
- apiGroups: ["beta.appgate.com"]
  resources: ["policies", "entitlements", "conditions"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appgate-operator
  namespace: appgate-test-1
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: appgate-operator
  apiGroup: rbac.authorization.k8s.io
