apiVersion: v1
kind: Pod
metadata:
  name: appgate-operator
  namespace: appgate-test-1
spec:
  containers:
  - name: appgate-operator
    image: atuindev/appgate-operator:latest
    env:
      - name: APPGATE_OPERATOR_NAMESPACE
        value: appgate-test-1
      - name: APPGATE_OPERATOR_USER
        valueFrom:
          secretKeyRef:
            name: appgate-operator-creds
            key: appgate-operator-user
      - name: APPGATE_OPERATOR_PASSWORD
        valueFrom:
          secretKeyRef:
            name: appgate-operator-creds
            key: appgate-operator-password
      - name: APPGATE_OPERATOR_HOST
        valueFrom:
          configMapKeyRef:
            name: appgate-operator-conf
            key: appgate-operator-host
      - name: APPGATE_OPERATOR_TIMEOUT
        valueFrom:
          configMapKeyRef:
            name: appgate-operator-conf
            key: appgate-operator-timeout
  imagePullSecrets:
    - name: appgate-registry
